// Post API 定义，包含博客文章的请求和响应消息

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Post) Default() {
}

func (x *CreatePostRequest) Default() {
}

func (x *CreatePostResponse) Default() {
}

func (x *UpdatePostRequest) Default() {
}

func (x *UpdatePostResponse) Default() {
}

func (x *DeletePostRequest) Default() {
}

func (x *DeletePostResponse) Default() {
}

func (x *GetPostRequest) Default() {
}

func (x *GetPostResponse) Default() {
}

func (x *ListPostRequest) Default() {
}

func (x *ListPostResponse) Default() {
}
