// User API 定义，包含用户信息、登录请求和响应等相关消息

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *User) Default() {
}

func (x *LoginRequest) Default() {
}

func (x *LoginResponse) Default() {
}

func (x *RefreshTokenRequest) Default() {
}

func (x *RefreshTokenResponse) Default() {
}

func (x *ChangePasswordRequest) Default() {
}

func (x *ChangePasswordResponse) Default() {
}

func (x *CreateUserRequest) Default() {
	if x.Nickname == nil {
		v := string("你好世界")
		x.Nickname = &v
	}
}

func (x *CreateUserResponse) Default() {
}

func (x *UpdateUserRequest) Default() {
}

func (x *UpdateUserResponse) Default() {
}

func (x *DeleteUserRequest) Default() {
}

func (x *DeleteUserResponse) Default() {
}

func (x *GetUserRequest) Default() {
}

func (x *GetUserResponse) Default() {
}

func (x *ListUserRequest) Default() {
}

func (x *ListUserResponse) Default() {
}
